### ISSUE TITLE
只通过ip如何进行https反代

### ISSUE THREAD

**Issue by KiritoGuugk** [bddjr/nginx-proxy-docs-for-mcsm#12]
国内的机器没有备案所以无法通过域名访问，在不备案的情况下应该如何配置https反代呢

**Comment by bddjr** [comment]
这种情况通常仅限于部分大厂IDC的机子。小厂IDC的机子通常不会有这种限制，只需要避开80 443端口即可正常访问。  
如果你用的就是大厂的服务器，那么可能（我听别人说的）根本无法建立任何https连接，  

但你的问题是使用IP进行https访问，或许可以试试 https://zerossl.com/ 输入IP签个证书，然后nginx配置的面对公网的部分的`server_name`也改成对应的公网IP

**Comment by KiritoGuugk** [comment]
> 这种情况通常仅限于部分大厂IDC的机子。小厂IDC的机子通常不会有这种限制，只需要避开80 443端口即可正常访问。 如果你用的就是大厂的服务器，那么可能（我听别人说的）根本无法建立任何https连接，
> 
> 但你的问题是使用IP进行https访问，或许可以试试 https://zerossl.com/ 输入IP签个证书，然后nginx配置的面对公网的部分的`server_name`也改成对应的公网IP
可以了，我用的是国内的腾讯云， zerossl签了ip证书，现在可以正常使用了。突然想到，是不是也可以用frp把这台腾讯云的24444端口转发到国外小鸡上，再进行反代？

**Comment by bddjr** [comment]
大厂应该不限制frp，所以理论上可行，但没必要。  
感谢您对实际情况做出反馈，我将会根据这个反馈，继续完善文章的内容。
